import {useState} from 'react';
import {Empty,format} from '../components/common';
import type {SavedRun} from '../types';
export function History({runs,onOpen,onDelete,onUndo,canUndo,onStart}:{runs:SavedRun[];onOpen:(r:SavedRun)=>void;onDelete:(id:string)=>void;onUndo:()=>void;canUndo:boolean;onStart:()=>void}) {
  const [selected,setSelected] = useState<string[]>([]);
  const pair = selected.map(id=>runs.find(r=>r.id===id)).filter((r):r is SavedRun=>!!r);
  function toggle(id:string) {setSelected(p=>p.includes(id)?p.filter(v=>v!==id):p.length<2?[...p,id]:p);}
  return <>
    <div className="page-title"><div><p className="eyebrow">ЛОКАЛЬНАЯ ИСТОРИЯ</p><h1>Сценарии города</h1><p className="subtitle">Успешные расчёты в этом браузере. Выберите два для сравнения.</p></div><button className="secondary" onClick={onStart}>К текущему плану</button></div>
    {canUndo && <div className="notice" role="status">Сценарий удалён из истории. <button className="text-button" onClick={onUndo}>Отменить удаление</button></div>}
    {!runs.length?<Empty title="Здесь будут ваши расчёты" action={onStart}>Рассчитайте первый план. Его название, решения, каталог и ответ Go сохранятся автоматически.</Empty>:<>
      <div className="history-grid">{runs.map(r=><article className="panel history-card" key={r.id}><label className="compare-check"><input type="checkbox" checked={selected.includes(r.id)} disabled={!selected.includes(r.id)&&pair.length===2} onChange={()=>toggle(r.id)}/>Сравнить{!selected.includes(r.id)&&pair.length===2?' — уже выбраны два':''}</label><h2>{r.name}</h2><p className="help">{new Date(r.createdAt).toLocaleString('ru-RU')}</p><div className="history-score">{format(r.result.final_score)} <small>Score</small></div><p>Бюджет: {r.result.total_cost} · остаток: {r.result.remaining_budget}</p><ul className="history-measures">{r.result.decisions.map(d=><li key={d.measure_id}>{d.measure_id} · {r.scenario.measures.find(m=>m.id===d.measure_id)?.name}{d.district_id?` — ${r.scenario.districts.find(x=>x.id===d.district_id)?.name}`:' — Весь город'}</li>)}</ul><div className="history-actions"><button className="secondary" onClick={()=>onOpen(r)}>Открыть результат</button><button className="text-button danger" onClick={()=>{onDelete(r.id);setSelected(p=>p.filter(id=>id!==r.id));}} aria-label={`Удалить сценарий ${r.name}`}>Удалить</button></div></article>)}</div>
      {pair.length===2?<Comparison a={pair[0]} b={pair[1]}/>:<p className="help" role="status">Выбрано для сравнения: {pair.length} из 2.</p>}
    </>}
  </>;
}
function Comparison({a,b}:{a:SavedRun;b:SavedRun}) {
  const same=a.datasetKey===b.datasetKey;
  const districtIds=Array.from(new Set([...a.result.district_before_after,...b.result.district_before_after].map(d=>d.district_id)));
  const criticalKeys=Array.from(new Set([a,b].flatMap(run=>run.result.district_before_after.flatMap(d=>run.scenario.indicator_order.filter(k=>d.before[k]<run.scenario.scoring.critical_threshold||d.after[k]<run.scenario.scoring.critical_threshold).map(k=>`${d.district_id}/${k}`)))));
  return <section className="panel comparison" aria-label="Сравнение двух сценариев"><div className="section-heading"><div><h2>Два плана — два результата</h2><p>{same?'Снимки исходных данных и правил совпадают.':'Исходные данные или правила отличаются.'}</p></div></div>
    <div className={`notice ${same?'':'warning'}`}>{same?'Backend не сообщает версию движка. Сопоставимость подтверждена по сохранённому каталогу, но не по версии Go.':'Эти результаты нельзя считать полностью сопоставимыми. Ниже — отдельные значения каждого ответа Go, без определения победителя.'}</div>
    <div className="table-scroll" tabIndex={0} role="region" aria-label="Сравнение показателей"><table className="comparison-table"><caption className="sr-only">Сравнение {a.name} и {b.name}</caption><thead><tr><th scope="col">Показатель</th><th scope="col">{a.name}</th><th scope="col">{b.name}</th></tr></thead><tbody>{([['Score до','base_score'],['Score после','final_score'],['Изменение Score','score_delta'],['Потрачено','total_cost'],['Остаток бюджета','remaining_budget'],['Критических до','critical_before'],['Критических после','critical_after']] as const).map(([label,key])=><tr key={key}><th scope="row">{label}</th><td>{format(a.result[key])}</td><td>{format(b.result[key])}</td></tr>)}{districtIds.map(id=><tr key={id}><th scope="row">{a.scenario.districts.find(d=>d.id===id)?.name || b.scenario.districts.find(d=>d.id===id)?.name} · Score до → после</th>{[a,b].map(run=>{const d=run.result.district_before_after.find(d=>d.district_id===id);return <td key={run.id}>{d?`${format(d.score_before)} → ${format(d.score_after)}`:'Нет данных'}</td>})}</tr>)}</tbody></table></div>
    <h3 className="panel-text">Критические показатели хотя бы в одном состоянии</h3>{criticalKeys.length?<div className="table-scroll" tabIndex={0} role="region" aria-label="Сравнение критических показателей"><table className="comparison-table"><caption className="sr-only">Критические показатели: до → после</caption><thead><tr><th scope="col">Район / показатель</th>{[a,b].map(run=><th scope="col" key={run.id}>{run.name}<span>Порог &lt; {run.scenario.scoring.critical_threshold}</span></th>)}</tr></thead><tbody>{criticalKeys.map(key=>{const [id,k]=key.split('/');return <tr key={key}><th scope="row">{a.scenario.districts.find(d=>d.id===id)?.name||id} · {a.scenario.indicator_names[k as keyof typeof a.scenario.indicator_names]||k}</th>{[a,b].map(run=>{const d=run.result.district_before_after.find(d=>d.district_id===id);const m=k as keyof NonNullable<typeof d>['after'];return <td key={run.id}>{d?<><span className={d.before[m]<run.scenario.scoring.critical_threshold?'danger':''}>{format(d.before[m])}</span> → <strong className={d.after[m]<run.scenario.scoring.critical_threshold?'danger':''}>{format(d.after[m])}{d.after[m]<run.scenario.scoring.critical_threshold?' !':''}</strong></>:'Нет данных'}</td>})}</tr>})}</tbody></table></div>:<p className="panel-text">В этих ответах критических значений нет.</p>}
  </section>;
}
