import {useState} from 'react';
import {ArrowRight, ArrowUpRight, Check, Info} from 'lucide-react';
import {categories, type Scenario} from '../types';
import {CategoryIcon, format} from '../components/common';
import {Skyline} from '../components/Skyline';
export function Overview({scenario:s,onStart,onAutopilot}:{scenario:Scenario;onStart:()=>void;onAutopilot?:()=>void}) {
  const [selected,setSelected] = useState(s.districts.find(d=>d.id==='nura')?.id || s.districts[0].id);
  const district = s.districts.find(d=>d.id===selected) || s.districts[0];
  const threshold = s.scoring.critical_threshold;
  return <>
    <section className="city-hero"><div><p className="eyebrow">АКИМ НА 5 ЧАСОВ / АСТАНА</p><h1>Город в ваших руках</h1><p className="subtitle">Задайте цель AI или выберите пять решений сами.<br/>Посмотрите, что изменится за {s.horizon_quarters} кварталов.</p>{onAutopilot&&<button className="cta" onClick={onAutopilot}>Поручить план AI <ArrowRight size={19}/></button>}<button className="secondary" onClick={onStart}>Составить план <ArrowRight size={19}/></button></div><Skyline/></section>
    <section className="stats overview-stats" aria-label="Условия сценария"><div className="stat primary"><div>Доступный бюджет</div><strong>{s.budget} <small>ед.</small></strong><p>На весь план развития</p></div><div className="stat"><div>Решения в вашем плане</div><strong>{s.required_decisions} <small>мер</small></strong><p>Не больше {s.max_measures_per_category} одного направления</p></div><div className="stat"><div>Город в деталях</div><strong>{s.districts.length} <small>районов</small></strong><p>{s.indicator_order.length} показателей в каждом</p></div></section>
    <section className="city-panel"><div className="section-heading"><div><h2>Пульс районов</h2><p>Шкала 0–100. Чем выше, тем лучше.</p></div><span className="legend">! Ниже {threshold} — критическое значение</span></div><div className="table-scroll" role="region" aria-label="Исходные показатели районов, таблица с горизонтальной прокруткой" tabIndex={0}><table><caption className="sr-only">Исходные показатели. Выберите район для подробностей.</caption><thead><tr><th scope="col">РАЙОН / НАСЕЛЕНИЕ</th>{s.indicator_order.map(m=><th scope="col" key={m}>{m}<span>{s.indicator_names[m]}</span></th>)}</tr></thead><tbody>{s.districts.map(d=><tr key={d.id} className={selected===d.id?'selected':''}><td><button onClick={()=>setSelected(d.id)} aria-pressed={selected===d.id}><span className="district-initial">{d.name[0]}</span><span><strong>{d.name}</strong><small>{format(d.population_share*100)}% населения</small></span>{selected===d.id?<Check size={16}/>:<ArrowUpRight size={16}/>}</button></td>{s.indicator_order.map(m=><td key={m}><span className={`heat ${d.indicators[m]<threshold?'critical':d.indicators[m]>=60?'high':'normal'}`} aria-label={`${s.indicator_names[m]}: ${d.indicators[m]}${d.indicators[m]<threshold?', критическое значение':''}`}>{d.indicators[m]}{d.indicators[m]<threshold && <span aria-hidden="true">!</span>}</span></td>)}</tr>)}</tbody></table></div><div className="table-note"><Info size={17}/> Выберите район, чтобы изучить показатели подробнее</div></section>
    <div className="bottom-grid"><section className="detail"><div className="section-heading"><div><p className="eyebrow">В ФОКУСЕ</p><h2>Район {district.name}</h2></div><span className="tag">{format(district.population_share*100)}% населения</span></div><div className="metric-groups">{categories.map((c,i)=><div className="metric-group" key={c}><h3><CategoryIcon category={c}/>{s.category_names[c]}</h3>{s.indicator_order.slice(i*2,i*2+2).map(m=><div className="metric" key={m}><div><span>{s.indicator_names[m]}</span><strong className={district.indicators[m]<threshold?'danger':''}>{district.indicators[m]}{district.indicators[m]<threshold?' !':''}</strong></div><div className="track" aria-hidden="true"><span className={district.indicators[m]<threshold?'low':''} style={{width:`${district.indicators[m]}%`}}/></div></div>)}</div>)}</div></section><section className="callout"><p className="eyebrow">ОТ ДАННЫХ К ДЕЙСТВИЮ</p><h2>Какой будет<br/>Астана завтра?</h2><p>Каждая мера имеет цену, область действия и срок до начала эффекта. Найдите баланс между потребностями районов.</p><p>Итоговый Score появится после расчёта вашего плана.</p><button className="cta" onClick={onStart}>К решениям <ArrowRight size={18}/></button></section></div>
  </>;
}
